name: Build and Distribute to Firebase

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

#      - name: Upload APK artifact t
#        uses: actions/upload-artifact@v3
#        with:
#          name: release-apk
#          path: app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Verify APK Location
        run: |
          ls -la app/build/outputs/apk/release/
          ls -la app/build/outputs/apk/

      - name: Distribute via Firebase
        if: github.ref == 'refs/heads/master'
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers  # Comma-separated list of tester groups
          file: app/build/outputs/apk/release/app-release-unsigned.apk